# Generated by Django 5.2.1 on 2025-05-21 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_user_user1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User1',
        ),
    ]
